/*
 miq 1.12.0
 @copyright 2016 Edwin Martin
 @see {@link http://www.bitstorm.org/javascript/miq/}
 @license MIT
*/
'use strict';self.miq=function(a,b){b=b&&b.first||b||document;if(typeof a=="function")b.readyState=="loading"?b.addEventListener("DOMContentLoaded",a):a();else{var c=Object.create(miq.b),d;if(typeof a=="object")if("length"in a){c.length=a.length;for(b=0;b<a.length;b++)c[b]=a[b]}else{c[0]=a;c.length=1}else if(a)if(d=a.match(/<(.+)>/)){c[0]=b.createElement(d[1]);c.length=1}else c=miq(b.querySelectorAll(a));else{c[0]=b.createDocumentFragment();c.length=1}return c}};
miq.b=Object.create(Array.prototype,{first:{get:function(){return this[0]}},s:{value:function(a){return miq(this[a||0])}},w:{value:function(a,b){for(var c=0;c<this.length;c++)this[c].addEventListener(a,b);return this}},v:{value:function(a,b){for(var c=0;c<this.length;c++)this[c].removeEventListener(a,b);return this}},h:{value:function(a){for(var b=0;b<this.length;b++)if(!miq.b.g.call({first:this[b]},a))this[b].className=this[b].className+(" "+a);return this}},B:{value:function(a){for(var b=0;b<this.length;b++)this[b].className=
this[b].className.replace(a,"");return this}},g:{value:function(a){return this.first.className!=""&&(new RegExp("\\b"+a+"\\b")).test(this.first.className)}},a:{value:function(a,b){if(typeof b=="undefined")return this.first[a];for(var c=0;c<this.length;c++)this[c][a]=b;return this}},l:{value:function(a,b){if(typeof b=="undefined")return this.first.getAttribute(a);for(var c=0;c<this.length;c++)this[c].setAttribute(a,b);return this}},A:{value:function(a){for(var b=0;b<this.length;b++)this[b].removeAttribute(a);
return this}},C:{value:function(a){var b=this.first,c="value";switch(b.tagName){case "SELECT":c="selectedIndex";break;case "OPTION":c="selected";break;case "INPUT":if(b.type=="checkbox"||b.type=="radio")c="checked"}return this.a(c,a)}},append:{value:function(a){a=miq(a);for(var b=a.length,c=0;c<b;c++)this.first.appendChild(a[c].first||a[c]);return this}},m:{value:function(a){this.first.parentElement.insertBefore(miq().append(a).first,this.first);return this}},parent:{value:function(){return miq(this.first.parentNode)}},
clone:{value:function(){return miq(this.first.cloneNode(true))}},remove:{value:function(){for(var a=0;a<this.length;a++)this[a].parentNode.removeChild(this[a]);return this}},find:{value:function(a){return miq(a,this.first)}},closest:{value:function(a){var b=this.first;do if(b[miq.matches](a))return miq(b);while(b=b.parentElement);return null}},is:{value:function(a){return miq(this.filter(function(b){return b[miq.matches](a)}))}},o:{value:function(a,b){if(typeof b=="undefined")return this.first.style[a];
for(var c=0;c<this.length;c++)this[c].style[a]=b;return this}},u:{value:function(a){return this.a("innerHTML",a)}},text:{value:function(a){return this.a("textContent",a)}}});miq.miq="1.12.0";
miq.c=function(a,b,c,d){var e=new XMLHttpRequest;e.onreadystatechange=function(){if(e.readyState==4)if(e.status==200){switch(d.dataType){case "xml":var a=e.responseXML;break;case "json":a=JSON.parse(e.responseText);break;default:a=e.responseText}b(a)}else c&&c("Ajax error: "+e.status)};e.open(d.method||"GET",a,true);if(d.headers)for(var f in d.headers)e.setRequestHeader(f,d.headers[f]);e.send(d.data||"")};miq.i=function(a,b){return new Promise(function(c,d){miq.c(a,c,d,b)})};
miq.matches=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector"].filter(function(a){return a in document.documentElement})[0];typeof define==="function"&&define.j?define(function(){return miq}):typeof module==="object"&&module.f?module.f=miq:typeof $=="undefined"&&($=miq);